name: Flutter CI

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Validar e Buildar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependências (pub get)
        run: flutter pub get

      - name: Analisar o código (Lint)
        run: flutter analyze

      - name: Build do APK
        run: flutter build apk --release
